# Mongoid Configuration for MongoHQ on Cloudfuji
# ============================================

development:
  host: localhost
  database: errbit_development

test:
  host: localhost
  database: errbit_test

production:
  uri: <%= ENV['MONGODB_URL'] %>
